name: morcus.net CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - dev

jobs:
  presubmit-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 6

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Installing npm dependencies
        run: npm ci
      - name: Installing Python dependencies
        run: pip install -r requirements.txt
      - name: Running unit tests
        run: npm run coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: ./coverage
      - name: Checking formatting
        run: npm run format-check

  prod-build:
    runs-on: ubuntu-latest
    timeout-minutes: 6

    steps:
      - uses: actions/checkout@v3
      - name: Installing npm dependencies
        run: npm install
      - name: Running prod build step
        run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: build_outputs
          path: |
            genfiles_static/
            library_processed/
            ls.db
            sh.db
            lat_infl.db

  integration-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 6

    steps:
      - uses: actions/checkout@v3
      - name: Installing npm dependencies
        run: npm ci
      - name: Running integration checks
        run: npm run integration-tests

  pytype-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 6

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Installing Python dependencies
        run: pip install -r requirements.txt
      - name: Checking Pytype
        run: npm run pytype
