name: morcus.net CI

on:
  push:
    branches:
    - main
    - dev
  pull_request:
    branches:
    - dev

jobs:
  presubmit-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 6

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Installing npm dependencies
        run: npm ci
      - name: Installing Python dependencies
        run: pip install -r requirements.txt
      - name: Running unit tests
        run: npm run coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: ./coverage
      - name: Checking formatting
        run: npm run format-check

  integration-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 6

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Installing npm dependencies
        run: npm ci
      - name: Installing Python dependencies
        run: pip install requests
      - name: Running integration checks
        run: python src/integration/e2e_test.py

  pytype-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 6

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Installing Python dependencies
        run: pip install -r requirements.txt
      - name: Checking Pytype
        run: npm run pytype
